project:
  type: website

website:
  title: "MaeLSTRoMWorks"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: gitlab
        href: https://gitlab.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/mlem
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



