project:
  type: website
  output-dir: site

website:
  title: "Dawith Lim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plots.qmd
        text: Portfolio
    right:
      - icon: github
        href: https://github.com/MangledPotat0
      - icon: linkedin
        href: https://www.linkedin.com/in/mlem
      - text: "Scholar"
        href: https://scholar.google.com/citations?hl=en&user=afpmAQMAAAAJ

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
execute:
  enabled: true

metadata-files:
  - _quarto.yml

languages:
  python:
    engine: "python"
